### PR TITLE
support any matchers

### PR DESCRIPTION
**Pull request by LumaKernel**
resolves https://github.com/LumaKernel/ddc-file/issues/6

## overview

image

(setting `ignoreCase`, use [`ddc-matcher_fuzzy`](https://github.com/matsui54/ddc-matcher_fuzzy) for matcher)

image
correctly completing filenames non-keyword included.

image

and fuzzy matching is also working with starting completion after non-keyword.

## changes

- it enables to use any matchers
  - at first, I thought it can be used with matcher that satisfies [∀a,b,c match(ab,ac) ⇒ match(b,c)], but it is used for completiong `aaaa.bbbb.cccc` for `aa.bb|` for example but it is essentially impossible so we should not care about this case.
  - [∀a,b,c match(ab,ac) ⇒ match(b,c)] is now only meaning _"the condition for matcher that the meaning is not broken in completion after the non-keyword filename"_ .
  - ya, no need to care, it supports any type of matchers.
- revert the usage of 'abbr'
  - it wasn't helpful. just showing `bbbb.cccc.dddd` even if the filename is `aaaa.bbbb.cccc.dddd`
- stop caring `ignoreCase` params from source.
  - it is not related to https://github.com/LumaKernel/ddc-file/pull/3 , but eventually this PR seems taking it in.
  - it is for matchers which cares alphabet's cases.
  - off-topic: I still think ddc.vim's behavior that `ignoreCase` is passed as `false` when setting `true` in wildcard(\_) is still bug, because `ignoreCase` in wildcard doesn't work for ddc-around.

### CODE REVIEW

**Comment by LumaKernel** [comment]
hmmmm.... so I should not care about `maxCandidates` options from source.
It effects users thinking _"want to match many files but show only few of them"_.

**Comment by Shougo** [comment]
> off-topic: I still think ddc.vim's behavior that ignoreCase is passed as false when setting true in wildcard(_) is still bug, because ignoreCase in wildcard doesn't work for ddc-around.

Really??  I have tested the minimal vimrc and it works!
Please create the new issue in ddc issues.  I will try it later.

**Comment by LumaKernel** [comment]
Very sorry, it was my configuration mistake 🙇 🙇

**Comment by Shougo** [comment]
Oh...

**Pull request merged**
